OP-1304 Policies App: Language switching does not work
openimis/imis_android_app_java pull request #178
Opened 2023-03-08 08:51 UTC by malinowskikam

[https://openimis.atlassian.net/browse/OP-1304](https://openimis.atlassian.net/browse/OP-1304)

Changes:
- Fixed tchad translations file structure

2023-03-08 13:55 UTC, dragos-dobre requested changes

2023-03-08 13:55 UTC, dragos-dobre commented on app/build.gradle
> +        tchadDev.res.srcDirs = ['src/tchad/res', 'src/localeBepha/res']
@malinowskikam Is 'src/localeBepha/res' the right folder? I see the Tchad res in 'src/localeTchad/res'?

2023-03-09 08:50 UTC, malinowskikam commented on app/build.gradle
> +        tchadDev.res.srcDirs = ['src/tchad/res', 'src/localeBepha/res']
Sorry, I fixed that.

2023-03-10 15:48 UTC, dragos-dobre approved these changes

2023-03-10 15:48 UTC, merged